/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MotionIndexRouteImport } from './routes/motion.index'
import { Route as WorkProjectIdRouteImport } from './routes/work.$projectId'
import { Route as MotionVideoSlugRouteImport } from './routes/motion.$videoSlug'

const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionIndexRoute = MotionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MotionRoute,
} as any)
const WorkProjectIdRoute = WorkProjectIdRouteImport.update({
  id: '/work/$projectId',
  path: '/work/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionVideoSlugRoute = MotionVideoSlugRouteImport.update({
  id: '/$videoSlug',
  path: '/$videoSlug',
  getParentRoute: () => MotionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/motion': typeof MotionRouteWithChildren
  '/motion/$videoSlug': typeof MotionVideoSlugRoute
  '/work/$projectId': typeof WorkProjectIdRoute
  '/motion/': typeof MotionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/motion/$videoSlug': typeof MotionVideoSlugRoute
  '/work/$projectId': typeof WorkProjectIdRoute
  '/motion': typeof MotionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/motion': typeof MotionRouteWithChildren
  '/motion/$videoSlug': typeof MotionVideoSlugRoute
  '/work/$projectId': typeof WorkProjectIdRoute
  '/motion/': typeof MotionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/motion'
    | '/motion/$videoSlug'
    | '/work/$projectId'
    | '/motion/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/motion/$videoSlug' | '/work/$projectId' | '/motion'
  id:
    | '__root__'
    | '/'
    | '/motion'
    | '/motion/$videoSlug'
    | '/work/$projectId'
    | '/motion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MotionRoute: typeof MotionRouteWithChildren
  WorkProjectIdRoute: typeof WorkProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion/': {
      id: '/motion/'
      path: '/'
      fullPath: '/motion/'
      preLoaderRoute: typeof MotionIndexRouteImport
      parentRoute: typeof MotionRoute
    }
    '/work/$projectId': {
      id: '/work/$projectId'
      path: '/work/$projectId'
      fullPath: '/work/$projectId'
      preLoaderRoute: typeof WorkProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion/$videoSlug': {
      id: '/motion/$videoSlug'
      path: '/$videoSlug'
      fullPath: '/motion/$videoSlug'
      preLoaderRoute: typeof MotionVideoSlugRouteImport
      parentRoute: typeof MotionRoute
    }
  }
}

interface MotionRouteChildren {
  MotionVideoSlugRoute: typeof MotionVideoSlugRoute
  MotionIndexRoute: typeof MotionIndexRoute
}

const MotionRouteChildren: MotionRouteChildren = {
  MotionVideoSlugRoute: MotionVideoSlugRoute,
  MotionIndexRoute: MotionIndexRoute,
}

const MotionRouteWithChildren =
  MotionRoute._addFileChildren(MotionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MotionRoute: MotionRouteWithChildren,
  WorkProjectIdRoute: WorkProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
